In [1]:
import os  
import pandas as pd

In [6]:
import pandas as pd
from IPython.display import display

# Define file path
file_path = r"C:\Users\Pinda\Downloads\mort2023ps\VS23MORT.DPSMCPUB_r20241030"

# Define colspecs and column names
colspecs = [
    (68, 69),     # Sex
    (83, 84),     # Place of death
    (84, 85),     # Marital Status
    (85, 86),     # Day of Week of Death
    (106, 107),   # Injury at Work
    (107, 108),   # Manner of Death
    (108, 109),   # Method of Disposition
    (109, 110),   # Autopsy
    (144, 145),   # Activity Code
    (145, 146),   # Place of Injury
    (146, 150),   # ICD-10 Cause of Death
    (154, 157),   # 113 Cause Recode
    (450, 451),   # Race Recode 6
    (484, 487),   # Hispanic Origin
    (487, 489),   # Hispanic Origin / Race Recode
]

column_names = [
    'Sex', 'PlaceOfDeath', 'MaritalStatus', 'DayOfWeek',
    'InjuryAtWork', 'MannerOfDeath', 'DispositionMethod', 'Autopsy',
    'ActivityCode', 'PlaceOfInjury', 'ICD10Cause', 'Cause113Recode',
    'RaceRecode6', 'HispanicOrigin', 'HispanicRaceRecode'
]

# Load data sample
df = pd.read_fwf(file_path, colspecs=colspecs, names=column_names, nrows=10000)

# Display first 20 rows nicely
display(df.head(20)) 

df.to_csv("mortality_stats.csv")

,Sex,PlaceOfDeath,MaritalStatus,DayOfWeek,InjuryAtWork,MannerOfDeath,DispositionMethod,Autopsy,ActivityCode,PlaceOfInjury,ICD10Cause,Cause113Recode,RaceRecode6,HispanicOrigin,HispanicRaceRecode
0,F,W,3,NaN,7.0,B,U,NaN,NaN,C,4430,43,NaN,1,21
1,F,S,3,NaN,7.0,B,U,NaN,NaN,F,0191,11,NaN,1,21
2,M,W,1,NaN,7.0,B,N,NaN,NaN,U,0710,18,NaN,1,21
3,M,M,2,NaN,7.0,C,N,NaN,NaN,I,4612,68,NaN,0,80
4,F,W,4,NaN,7.0,B,N,NaN,NaN,F,03 1,11,NaN,1,21
5,M,M,4,NaN,7.0,B,N,NaN,NaN,B,1820,15,NaN,1,32
6,M,D,5,NaN,2.0,B,N,NaN,0.0,X,70 4,26,NaN,1,21
7,F,W,7,NaN,7.0,B,N,NaN,NaN,J,4492,86,NaN,1,21
8,F,M,1,NaN,7.0,C,N,NaN,NaN,I,4612,68,NaN,1,10
9,F,U,2,NaN,7.0,B,N,NaN,NaN,C,2590,25,NaN,1,21
10,M,M,2,NaN,7.0,C,N,NaN,NaN,I,1192,56,NaN,1,10
11,M,M,4,NaN,7.0,B,N,NaN,9.0,W,80 4,23,NaN,1,10
12,M,W,3,NaN,7.0,B,N,NaN,NaN,I,1192,56,NaN,1,21
13,M,S,5,NaN,7.0,B,N,NaN,NaN,I,1192,56,NaN,1,21
14,M,M,6,NaN,7.0,B,N,NaN,NaN,K,7463,95,NaN,1,21
15,M,M,6,NaN,7.0,B,U,NaN,NaN,G,20 1,51,NaN,1,21
16,F,W,1,NaN,7.0,B,N,NaN,NaN,J,4492,86,NaN,1,21
17,M,S,4,NaN,7.0,C,N,NaN,NaN,I,5002,67,NaN,1,21
18,F,W,1,NaN,7.0,C,N,NaN,NaN,I,1192,56,NaN,1,11
19,M,M,3,NaN,7.0,B,N,NaN,NaN,I,2592,63,NaN,1,21